id: P009425
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC291
  title: ལཱ་མོ་སྐུ་ཕྲེང་བདུན་པ་དགེ་འདུན་བསྟན་འཛིན་ནོར་བུ་དཔལ་བཟང་པོའི་རྣམ་ཐར་དང་སྐུ་གདུང་མཆོད་རྟེན་དཀར་ཆག
  author: ''
  volumes: {}
