id: P009425
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC291
  title: ལཱ་མོ་སྐུ་ཕྲེང་བདུན་པ་དགེ་འདུན་བསྟན་འཛིན་ནོར་བུ་དཔལ་བཟང་པོའི་རྣམ་ཐར་དང་སྐུ་གདུང་མཆོད་རྟེན་དཀར་ཆག
  author: ''
  volumes:
    9143f798c07c4cc9ada0edf59ea6a505:
      image_group_id: I2PD18849
      title: ''
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
